#!/usr/bin/env python3
"""Fetch the pinned Caddy binary for Student Mode (classroom server).

Caddy (Apache-2.0) is bundled inside the engine's PyInstaller onedir so
the classroom reverse proxy travels with the app. This script downloads
the pinned release for the current (or requested) platform, verifies the
SHA256 against the table below, and drops the binary into
``engine/caddy-bin/`` (gitignored) where the PyInstaller spec picks it
up as ``caddy/``.

Usage:
    python scripts/fetch_caddy.py                 # current platform
    python scripts/fetch_caddy.py --os windows    # windows|macos-arm|macos-intel|linux
    python scripts/fetch_caddy.py --all           # all release platforms (CI matrix)

If a platform's binary is already present with the right checksum, the
download is skipped — safe to re-run in CI.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
import tarfile
import tempfile
import urllib.request
import zipfile
from pathlib import Path

CADDY_VERSION = "2.10.0"

# Verification hashes of the ARCHIVE files published on the Caddy GitHub
# release page. These are copied from the release's official
# caddy_2.10.0_checksums.txt — NOTE: Caddy's checksum file carries
# SHA-512 digests (128 hex chars), so that's what we verify with (stronger
# than sha256 and directly comparable to the official source).
# Generated by scripts/fetch_caddy.py --print-checksums after a verified
# download; keep in lockstep with CADDY_VERSION.
SHA512 = {
    "linux": "626682d623ca04356ab3c9a93a82386cfde6d8243b11f2d0eea9e97ba630c7ada62373401e96b72c6690c98ae8dd004d61fafe477f5249690d5cb251ebbfd2d9",
    "windows": "cb97adb2bff5de752e470486ae72d55a6ddcfe4bfa43f09ed849260955df7f61385ac1e2d28fc80458b6910d71fa38d4295bb0689263dcc1743f2050d847c2ad",
    "macos-arm": "05c4d572ca0283620740ec9c188ad4c8ac36a725ee55e9b39457d7b3c11decc8588d648fafbb4116f35fdec8497d606afffafee3ab3cb367fd33505bf5aea9ba",
    "macos-intel": "2c4890f45bf750a73f5114b383e18fd77f58298cdb0cf5f67672e0f8c56e73fad938c20f18f0a154d6d03a1eba5e1835ad047edd1b6c1253d6c857b4fec539a8",
}

ASSETS = {
    "linux": f"caddy_{CADDY_VERSION}_linux_amd64.tar.gz",
    "windows": f"caddy_{CADDY_VERSION}_windows_amd64.zip",
    "macos-arm": f"caddy_{CADDY_VERSION}_mac_arm64.tar.gz",
    "macos-intel": f"caddy_{CADDY_VERSION}_mac_amd64.tar.gz",
}

BASE_URL = f"https://github.com/caddyserver/caddy/releases/download/v{CADDY_VERSION}"
DEST_DIR = Path(__file__).resolve().parent.parent / "engine" / "caddy-bin"
EXE_NAME = {"linux": "caddy", "windows": "caddy.exe", "macos-arm": "caddy", "macos-intel": "caddy"}


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def sha512_of(path: Path) -> str:
    h = hashlib.sha512()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def detect_platform() -> str:
    if sys.platform.startswith("win"):
        return "windows"
    if sys.platform == "darwin":
        import platform

        return "macos-arm" if platform.machine() == "arm64" else "macos-intel"
    return "linux"


def _utf8_stdio() -> None:
    """Windows CI consoles default to cp1252, which cannot encode arrows
    and other box-drawing punctuation (→ crashed Release run #161). Force
    UTF-8 with a replace fallback so logging can never kill the job."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:  # noqa: BLE001, S110 — best-effort; any console is fine
            pass


def fetch(platform: str, dest_root: Path = DEST_DIR) -> int:
    asset = ASSETS[platform]
    url = f"{BASE_URL}/{asset}"
    exe_dest = dest_root / EXE_NAME[platform]
    expected = SHA512.get(platform, "")

    if exe_dest.is_file() and expected:
        # Cached binary: verify via a small sidecar hash we wrote at install
        # time (hashing the whole archive again isn't possible post-extract).
        stamp = dest_root / f".sha512-{platform}"
        if stamp.is_file() and stamp.read_text().strip() == expected:
            print(f"[skip] {platform}: {exe_dest} already present (verified at install)")
            return 0

    dest_root.mkdir(parents=True, exist_ok=True)
    print(f"[get ] {platform}: {url}")
    with tempfile.TemporaryDirectory() as tmp:
        archive = Path(tmp) / asset
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "CorpusMind-fetch_caddy/1.0"})
            with urllib.request.urlopen(req, timeout=120) as resp, archive.open("wb") as out:
                shutil.copyfileobj(resp, out)
        except Exception as exc:  # noqa: BLE001 — report any network failure
            print(f"[FAIL] download failed: {exc}")
            return 1

        if expected:
            got = sha512_of(archive)
            if got != expected:
                print(f"[FAIL] checksum mismatch for {asset}:\n  expected {expected}\n  got      {got}")
                return 1
            print(f"[ok  ] sha512 verified against Caddy's official checksums.txt: {got[:16]}...")
        else:
            print(f"[warn] no pinned checksum for {platform} in this script version — "
                  f"archive sha512 is {sha512_of(archive)}")

        # Extract just the caddy binary.
        if asset.endswith(".zip"):
            with zipfile.ZipFile(archive) as zf:
                member = next(n for n in zf.namelist() if n.endswith(EXE_NAME[platform]))
                with zf.open(member) as src, exe_dest.open("wb") as dst:
                    shutil.copyfileobj(src, dst)
        else:
            with tarfile.open(archive, "r:gz") as tf:
                member = next(m for m in tf.getmembers() if m.name.endswith("caddy"))
                with tf.extractfile(member) as src, exe_dest.open("wb") as dst:
                    shutil.copyfileobj(src, dst)
    if platform != "windows":
        exe_dest.chmod(0o755)
    if expected:
        (dest_root / f".sha512-{platform}").write_text(expected + "\n")
    print(f"[ok  ] {platform} -> {exe_dest} ({exe_dest.stat().st_size:,} bytes)")
    return 0


def main() -> int:
    _utf8_stdio()
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--os", choices=list(ASSETS), help="platform to fetch (default: current)")
    g.add_argument("--all", action="store_true", help="fetch every release platform into caddy-bin/<platform>/")
    g.add_argument(
        "--print-checksums",
        action="store_true",
        help="re-download each archive and print the sha512 line to pin (bypasses the cache)",
    )
    args = ap.parse_args()

    if args.print_checksums:
        # Download each archive fresh and print its sha512 (the digest this
        # script pins, matching Caddy's official checksums.txt format).
        rc = 0
        for platform, asset in ASSETS.items():
            url = f"{BASE_URL}/{asset}"
            print(f"[get ] {platform}: {url}")
            try:
                with tempfile.TemporaryDirectory() as tmp:
                    archive = Path(tmp) / asset
                    req = urllib.request.Request(
                        url, headers={"User-Agent": "CorpusMind-fetch_caddy/1.0"}
                    )
                    with urllib.request.urlopen(req, timeout=120) as resp, archive.open("wb") as out:
                        shutil.copyfileobj(resp, out)
                    print(f'    "{platform}": "{sha512_of(archive)}",')
            except Exception as exc:  # noqa: BLE001 — report any network failure
                print(f"[FAIL] {platform}: {exc}")
                rc = 1
        return rc

    if args.all:
        rc = 0
        for platform in ASSETS:
            per_platform_dir = DEST_DIR / platform
            if fetch(platform, per_platform_dir) != 0:
                rc = 1
        return rc

    return fetch(args.os or detect_platform())


if __name__ == "__main__":
    sys.exit(main())
